apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-prod
  annotations:
    kubernetes.io/ingress.class: "public"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - ctp.rcc.uq.edu.au
    secretName: ctp-rcc-uq-edu-au-tls
  rules:
  - host: ctp.rcc.uq.edu.au
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ctp-httpsimport
            port:
              number: 7777
